### ISSUE TITLE
Sort is ignored

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2354] opened 2023-03-30 15:16 UTC
### What's up?

```
from a=albums
sort album_id
take 10
join tracks [==album_id]
group [a.album_id, a.title] (aggregate price = (sum tracks.unit_price))
```

The sort function is silently ignored.
Either throw an error or move it automatically the to the bottom of the statement.

**Comment by eitsupi** [comment] 2023-03-30 15:31
FYI, dbplyr raises an error in such cases.
https://dbplyr.tidyverse.org/reference/arrange.tbl_lazy.html

**Comment by max-sixty** [comment] 2023-03-30 19:33
This is related to https://github.com/PRQL/prql/issues/1363.

Here's an even smaller example (FYI this would have been a good issue to put in a bug report)

```elm
from albums
sort album_id
group [album_id] (aggregate ct = count)
```

```sql
SELECT
  album_id,
  COUNT(*) AS ct
FROM
  albums
GROUP BY
  album_id

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)
```

Here, I think we probably should put `ORDER BY` at the bottom. 

---

That said, until we do, I'm not sure we should error — the current semantics are that `sort` is "cleared" by operations such as `GROUP BY`, similar to SQL. It would break the composability principle if adding an additional transform at the end caused previous transforms to raise an error.

**Comment by max-sixty** [comment] 2023-03-30 19:35
This is documented in https://prql-lang.org/book/transforms/sort.html#notes

Is there anything we can do that's not a full #1363? Otherwise we could defer to that. (...which is a sizeable issue, not intractable but not a quick fix either)

**Comment by max-sixty** [comment] 2023-04-09 01:49
Closing as dupe of #1363 with the current state documented. But please reopen if that misses anything

**Closed as completed by max-sixty** 2023-04-09 01:49 UTC
