### ISSUE TITLE
Possible join alias issue resulting in parsing error

### ISSUE THREAD

**Issue by dlescos** [PRQL/prql#284] opened 2022-03-30 09:36 UTC
(on windows)

```elm
from c_invoice
join doc:c_doctype [c_invoice_id]
select [
	invoice_no,
	docstatus
]
```

panics with `Failed to convert List([ListItem([Ident("c_invoice_id")])])`

but this works:
```elm
from c_invoice
join c_doctype [c_invoice_id]
select [
	invoice_no,
	docstatus
]
```

I've found this syntax in https://github.com/max-sixty/prql/blob/main/examples/employees-2.md

**Comment by max-sixty** [comment] 2022-03-30 19:09
Thanks a lot for the report @dlescos 

We'll fix this, and try and ensure it doesn't panic when there is a small bug; though I'm sure this won't be the last.

**Comment by max-sixty** [comment] 2022-04-01 05:45
Closed by https://github.com/max-sixty/prql/issues/284. This was caused by the parser not handling tabs.

Thanks @dlescos

**Closed as completed by max-sixty** 2022-04-01 05:45 UTC
Labels: bug
