### ISSUE TITLE
s-strings may insert spaces between some spacial characters

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1973] opened 2023-02-27 09:57 UTC
Reported in eitsupi/prqlr#92

If the s-string contains characters such as `!` or `?` etc., it seems that the strings in the s-strings is not passed directly to SQL.

For example:

```elm
from a
select s"?abc!efg"
```

Now I get:

```sql
SELECT
  ? abc ! efg
FROM
  a

-- Generated by PRQL compiler version:0.5.2 (https://prql-lang.org)
```

But I want to get:

```sql
SELECT
  ?abc!efg
FROM
  a
```

**Comment by aljazerzen** [comment] 2023-02-27 12:06
Duplicate of #1284

**Closed as not planned** 2023-02-27 12:07 UTC
Labels: bug, compiler
