### ISSUE TITLE
Readability of `switch` statement with long lines

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1922] opened 2023-02-21 23:38 UTC
The following code using `switch` works fine, but it's hard to read because of the long lines:

```
from sd=foo
select [
  CorrectedAssmt = switch [
  sd.SD_Appraisal2021 == sd.SD_Assessment2021 -> sd.SD_Assessment2021,
  sd.SD_Appraisal2021 != sd.SD_Assessment2021 and sd.SD_Appraisal2021 < 500000 -> sd.SD_Ass_Land2021+sd.SD_Ass_Imp2021/loVal,
  sd.SD_Appraisal2021 != sd.SD_Assessment2021 and sd.SD_Appraisal2021 >= 500000 -> sd.SD_Ass_Land2021+sd.SD_Ass_Imp2021/hiVal,
  ],
]
```
I was tempted to break the lines at `and` and `->` to look something like this:

```
from sd=foo
select [
  CorrectedAssmt = switch [
  sd.SD_Appraisal2021 == sd.SD_Assessment2021 
    -> sd.SD_Assessment2021,
  sd.SD_Appraisal2021 != sd.SD_Assessment2021 and
  sd.SD_Appraisal2021 < 500000
    -> sd.SD_Ass_Land2021+sd.SD_Ass_Imp2021/loVal,
  sd.SD_Appraisal2021 != sd.SD_Assessment2021 and 
  sd.SD_Appraisal2021 >= 500000 
    -> sd.SD_Ass_Land2021+sd.SD_Ass_Imp2021/hiVal,
  ],
]
```
but this gives errors: apparently the entire clause must be on the same line. 

I'm not sure if I consider this to be a language design problem: I just note the awkwardness in this situation.

**Comment by max-sixty** [comment] 2023-02-22 08:36
Yes this is a good case. 

IIRC we have an existing issue for linebreaks — could we add it to that if we do?

**Comment by richb-hanover** [comment] 2023-02-22 12:32
By all means. I am simply reporting an interesting use case, to be considered in the broader scope of the language. Thanks.

**Comment by max-sixty** [comment] 2023-02-22 15:25
OK, closing as dupe of https://github.com/PRQL/prql/issues/819, this can serve as a good case of that

**Closed as completed** 2023-02-22 15:26 UTC
