### ISSUE TITLE
Python PRQL compiler replaces identifiers with "$ name"

### ISSUE THREAD

**Issue by ArneBachmannDLR** [PRQL/prql#3286] opened 2023-08-08 09:43 UTC
### What happened?

I want to use identifiers to create a prepared statement, but the named identifiers, e.g., `filter asset_id == $r` are compiled down to `asset_id = $ r` which leads to an SQLite error (note the space). Other allowed notations like `:id` or `@id` are not supported by PRQL.

Usually I would use positional question marks for prepared statements like `WHERE asset_id=?`, but only named arguments are supported by PRQL, it seems. Using a dictionary to provide the parameters has the benefit of not needing to repeat arguments used in different places, but it doesn't seem to work:

```python3
compile("... filter (day > $sd || slot >= $ss)", {"sd": ..., "ed": ...})
```

leads to

```sql
AND day >= $ sd
AND day <= $ ed
```

### PRQL input

```elm
See above
```

### SQL output

```SQL
See above
```

### MVCE confirmation

- [ ] Minimal example
- [X] New issue

**Comment by max-sixty** [comment] 2023-08-08 14:28
Thanks @ArneBachmannDLR . 

This overlaps with https://github.com/PRQL/prql/issues/1284, and is probably a dupe of https://github.com/PRQL/prql/issues/3077. There's an upstream issue at https://github.com/shssoichiro/sqlformat-rs/issues/18.

A workaround for sqlite, which IIUC doesn't allow `$1` is an s-string with a `?`: 

```elm
from invoices
filter x == s"?"
```

```sql
SELECT
  *
FROM
  invoices
WHERE
  x = ?

-- Generated by PRQL compiler version:0.9.3 (https://prql-lang.org)

```

---

I do think the current situation here is pretty bad, and we should try and fix. It's marked as Priority. I'll close this as a duplicate, but feel free to subscribe to the other issue.

**Closed as not planned by max-sixty** 2023-08-08 14:28 UTC
Labels: bug

**Comment by ArneBachmannDLR** [comment] 2023-08-08 15:36
Thanks, that resolves it for me and is comparable to the original pure SQL implementation.
