### ISSUE TITLE
Right shift operator '>>' in s-string is broken by PRQL by white space insertion.

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#2487] opened 2023-04-25 10:41 UTC
### What happened?

Minor but critical problem. Maybe there is some clever escape/workaround?

### PRQL input

```elm
from invoices
derive [
  A = s"invoice_id >> 1"
]
```

### SQL output

```SQL
SELECT
  *,
  invoice_id > > 1 AS "A"
FROM
  invoices

-- Generated by PRQL compiler version:0.8.0 (https://prql-lang.org)
```

### Expected SQL output

```SQL
SELECT
  *,
  invoice_id >> 1 AS "A"
FROM
  invoices

-- Generated by PRQL compiler version:0.8.0 (https://prql-lang.org)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by cottrell** [comment] 2023-04-25 11:03
Workaround is to use basic math expressions and '%' (which works in prql s-strings).

**Comment by eitsupi** [comment] 2023-04-25 11:12
Thanks, but I think it is duplicate of #1284

**Closed as not planned by eitsupi** 2023-04-25 11:12 UTC
Labels: bug
