### ISSUE TITLE
Unexpected behaviour of `group` transform without aggregation

### ISSUE THREAD

**Issue by RalfNorthman** [PRQL/prql#1749] opened 2023-02-09 09:39 UTC
Maybe related to #1748

## The problem

Maybe my intuition regarding this is lacking but with this query:

```prql
from alb = albums
join t = tracks [t.album_id==alb.album_id]
join art = artists [art.artist_id==alb.artist_id]

# Songs shorter than 4 minutes
filter t.milliseconds < 4 * 60 * 1000

group [alb.album_id] (
    take 1
)

take 10
```

I expect the result to have just one row per album but that is not what happens as of version 0.5.0. The resulting sql have `SELECT DISTINCT` on **all** columns:

```sql
WITH table_1 AS (
  SELECT
    DISTINCT alb.*,
    t.*,
    art.*
  FROM
    albums AS alb
    JOIN tracks AS t ON t.album_id = alb.album_id
    JOIN artists AS art ON art.artist_id = alb.artist_id
  WHERE
    t.milliseconds < 240000
)
SELECT
  *,
  *,
  *
FROM
  table_1
LIMIT
  10

-- Generated by PRQL compiler version:0.5.0 (https://prql-lang.org)

```

## In contrast

If I add a `sort` transform inside the `group` I get a reasonable result (but I don't think I should _have to_ sort to get the behavior that I'm after):

```prql
from alb = albums
join t = tracks [t.album_id==alb.album_id]
join art = artists [art.artist_id==alb.artist_id]

# Songs shorter than 4 minutes
filter t.milliseconds < 4 * 60 * 1000

group [alb.album_id] (
    sort alb.album_id
    take 1
)

take 10
``` 

Similar query, but with aggregation also behaves as expected:

```prql
from alb = albums
join t = tracks [t.album_id==alb.album_id]
join art = artists [art.artist_id==alb.artist_id]

# Songs shorter than 4 minutes
filter t.milliseconds < 4 * 60 * 1000

group [alb.album_id] (
  aggregate [
    number_tracks = count
  ]
)

take 10
```

**Comment by aljazerzen** [comment] 2023-02-09 12:43
I believe this is duplicate of #944. Thanks for report anyway.

**Closed as completed by aljazerzen** 2023-02-09 12:43 UTC
