### ISSUE TITLE
Is there a way for force PRQL to include tables (created in PRQL) used in s-strings?

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#2467] opened 2023-04-17 16:10 UTC
### What's up?

Consider this example:

```prql
let A = (
from invoices
)

from s"select * from A using sample reservoir(10 rows) repeatable(0)"
```

compiles to

```sql
WITH table_0 AS (
  SELECT
    *
  from
    A using sample reservoir(10 rows) repeatable(0)
)
SELECT
  *
FROM
  table_0 AS table_1

-- Generated by PRQL compiler version:0.7.1 (https://prql-lang.org)
```

and results in the error

```
Error: Catalog Error: Table with name A does not exist!
Did you mean "pg_am"?
```

I think if we could simply tell the PRQL compiler to always include A somehow it might work. Not sure how complicated that is.

**Comment by cottrell** [comment] 2023-04-17 17:04
Some workaround FWIW

```prql
let A = (
from invoices
)

let pointless = (
from A
filter billing_city == 'asdfasdfasdf_definitely_nothing'
)

let sample = (
from s"select * from A using sample reservoir(3 rows) repeatable(0)"
)

from sample
append pointless
```

**Comment by max-sixty** [comment] 2023-04-17 21:10
~This was raised a while ago in https://github.com/PRQL/prql/issues/1199. I guess we closed it then, but:~
~- I would now prioritize solving the underlying issues more highly than back then, unless there's a workaround we can think of?~
~- The error we added in https://github.com/PRQL/prql/pull/1203 doesn't seem to work for this case, where the table name is in a `from`~

Update: actually https://github.com/PRQL/prql/issues/1762 is the current issue. Is there anything here that isn't covered there?

---

The basic issue is that s-strings don't yet support including table names. So this:

```elm
let foo = (
  from bar
)

from s"SELECT * from {foo}"
```

...just ignores what `foo` resolves to, and includes the literal term `foo`:

```sql
WITH table_0 AS (
  SELECT
    *
  from
    foo  -- This should be `bar`!
)
SELECT
  *
FROM
  table_0 AS table_1

-- Generated by PRQL compiler version:0.8.0 (https://prql-lang.org)
```

---

I'm not sure of the best short-term fix — s-strings **are** the escape hatch, so when they don't work, we're possibly out of escape hatches. (Your workaround is clever though!)

Any thoughts from others?

**Comment by ediphy-dwild** [comment] 2023-04-18 08:04
from my experimentation, i think the issue is that the creation of A is pruned from the output as it is 'not required'. if there was a hint that we could specify to force creation of A, it could then be referenced elsewhere and not be pruned. It seems that this is all the workaround is doing, in a roundabout manner

eg:

```
let A = (
from invoices
)

force_create A # <<<< don't prune variable A

let sample = (
from s"select * from A using sample reservoir(3 rows) repeatable(0)"
)

from sample
```

**Comment by aljazerzen** [comment] 2023-04-20 21:40
This:
```
let foo = (
  from bar
)

from s"SELECT * from {foo}"
```
... should include table `foo` in the query, since it's referenced from s-string. Which means this is a bug.

**Comment by max-sixty** [comment] 2023-04-20 21:47
I think we can close this in favor of https://github.com/PRQL/prql/issues/1762 — is there anything here that isn't covered by this?

**Closed as completed by max-sixty** 2023-04-20 21:47 UTC
Labels: bug
