### ISSUE TITLE
Support IN set of values

### ISSUE THREAD

**Issue by Baoqi** [PRQL/prql#747] opened 2022-07-01 07:47 UTC
Currently, seems the only supported "in" is like:

```
from employees
filter (age | in 20..80)
```

which will be translated to:

```
SELECT
  employees.*
FROM
  employees
WHERE
  age BETWEEN 20
  AND 80
```

Is there a way for IN Clause, like:

```
SELECT
  employees.*
FROM
  employees
WHERE
  dept IN ('tech', 'hr', 'sales')
```

**Comment by aljazerzen** [comment] 2022-07-01 10:12
Good point. 

I propose following syntax:
```elm
from employees
filter (dept | in ['tech', 'hr', 'sales'])
```
There is quite a lot of punctuation, WDYT?

**Comment by max-sixty** [comment] 2022-07-01 13:28
I think that's good!

Does this compile to the same SQL for most dialects?

**Comment by Baoqi** [comment] 2022-07-02 02:05
Yes, I think

 dept IN ('tech', 'hr', 'sales')

in SQL is supported by most dialects

**Comment by max-sixty** [comment] 2022-07-02 04:29
Great. We'd need to work out a way of distinguishing based on the type of the arg from the stdlib, which isn't yet supported, but could be supported by #593.

If that's difficult, we could add it into the compiler, which would be fairly easy-ish™

**Comment by PrettyWood** [comment] 2023-12-08 08:06
Duplicate of https://github.com/PRQL/prql/issues/993 and fixed in https://github.com/PRQL/prql/pull/3883

**Closed as completed by PrettyWood** 2023-12-08 08:06 UTC
Labels: enhancement, compiler
